### PR TITLE
Feat(build seq) codecov, use bash instead of npm module.

### LINKED ISSUE #1077: Improvement build sequence (codecov)
Well i am too excited to contribute to chai, so previous work #1073 seems have better way.
It's just 300kb , but in my point of view it save developers time to install it and save small disk space :smile: .
image
The better way is via [bash](https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-via-flag).

### PR DESCRIPTION
**Pull request by brutalcrozt**
Fix #1077

### CODE REVIEW

**Comment by keithamus** [comment]
Hey @brutalcrozt thanks for the issue.

I feel _really_ uncomfortable downloading and executing aribtrary bash on my local machine, and on CI (where we have secret tokens like account passwords). The 300k is only downloaded for developers/ci (where it is also heavily cached), so I think it's adequete to keep it. I'll close this issue, you did the right thing in the original PR, and changing to running arbitrary bash would be a bad move IMO.

**Comment by astorije** [comment]
Something I often see is adding the dependency in the build config itself and not `package.json`:

```
install:
  - npm install -g codecov
script:
  - ...
  - codecov
```

That would solve what you were trying to solve, @brutalcrozt, without relying on a bash download.

---

In fact, considering `codecov` is currently _not_ installed `-g`lobally, how come running `codecov` works? I'd expect to see `./node_modules/.bin/codecov` in there instead, unless Travis runs their `script` section from `./node_modules/.bin` itself.

**Comment by keithamus** [comment]
I believe Travis have `./node_modules/.bin` in the `PATH`. We could make travis install codecov independantly, but I would like to draw complexity _out_ of our travis scripts and into tooling that can work agnostic of CI - especially as I'd like to add appveyor into our toolchain for testing IE without saucelabs, so package.json feels right to me. Other should comment though, we should reach a consensus.

**Comment by meeber** [comment]
I like the self-documenting nature of keeping the dev dependency in `package.json`. I'd like to keep it as-is.

**Pull request closed without merging**
