### PR TITLE
fix indexing into array with deep propery

### PR DESCRIPTION
**Pull request by eldritch-fossicker**
* added unit test to expect with code from documentation
* added default to res in _getPathValue

### CODE REVIEW

**Comment by keithamus** [comment]
@eldritch-fossicker thanks very much for the PR, but I must admit I can't really tell what this is solving or doing. Could you please elaborate on your explanation with what this aims to fix; perhaps with examples of currently broken code that will be fixed by this PR? Thanks

**Comment by eldritch-fossicker** [comment]
certainly the I had a test that kept failing which was very similar to 
```javascript
expect(deepObj).to.have.property('teas')
  .that.is.an('array')
  .with.deep.property('[2]')
    .that.deep.equals({ tea: 'konacha' });
```
from the chain-able portion of the property documentation trying to walk into the array by index always failed. So, I added the snipped from the documentation to the unit tests. Then I solved the problem by changing `_getPathValue ` to return a value other than undefined to `info.parent` for a path of exactly 1

**Comment by keithamus** [comment]
I guess what is not making sense to me is the fix. It seems to be relying on a side-effect added to `_getPathValue` rather than explicitly tackling the problem. It feel as though the current fix is somewhere non-obvious and may well trip people up when refactoring. To me, it seems better to change [L35](https://github.com/eldritch-fossicker/chai/blob/master/lib/chai/utils/getPathInfo.js#L35) from:

```js
parent: _getPathValue(parsed, obj, parsed.length - 1),
```

to:

```js
parent: parsed.length > 1 ? _getPathValue(parsed, obj, parsed.length - 1) : obj,
```

As this is much more explicit as an indicator for what is going on. What are your thoughts @eldritch-fossicker?

**Comment by eldritch-fossicker** [comment]
@keithamus that will certainly fix the problem. My first conclusion with I looked at the function was that walking path to an index of  0 should return the object itself;  therefore, the function should fixed. I think  a conditional return or comment would be in order. But I'm just inserted in fixing the error whichever solution.

**Comment by keithamus** [comment]
I see where you're coming from now @eldritch-fossicker. Ultimately it's neither here nor there - but the original patch seems slightly less explicit. On your point about if it were called with an index of 0 - I'd suggest that it shouldn't be called at all if that is the case.

If you could amend the patch to my reflect my comments above I'd be very happy at merging this though :smile:

**Comment by keithamus** [comment]
:tada:

**Pull request merged**
