### PR TITLE
Add @vieiralucas to MAINTAINERS

### PR DESCRIPTION
**Pull request by vieiralucas**
Is this real life?

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Welcome aboard buddy!
It's an honor for us to have you on the team, that's a great achievement for the Lucas' Syndicate.

:tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by keithamus** [comment]
Very happy with this, but I won't say the magic word, as I want to get @meeber's approval here too 😄

**Comment by meeber** [comment]
No no no!

I refuse to say LGTM!

This will never get merged!

The Lucas Syndicate will never prevail!

**Comment by meeber** [comment]
Wait what?! "All checks have passed"?!??! How could this be??

Nooooooooooooo!

**Comment by meeber** [comment]
Sigh

**Comment by meeber** [comment]
Fine I suppose one more Lucas is okay.

BUT THIS IS THE FINAL ONE!

No more Luci after this.

**Pull request merged**
