### PR TITLE
Revert "Allows writing lint-friendly tests"

### PR DESCRIPTION
**Pull request by keithamus**
Reverts chaijs/chai#297

@logicalparadox @joshperry

### CODE REVIEW

**Comment by joshperry** [comment]
Just wonder if you guys are going to revert this or just leave it until people start to use the new syntax in their code... The chaijs website was also updated to document this new syntax. If we wait too long, reverting may end up being a backcompat issue.

**Comment by keithamus** [comment]
@joshperry indeed. `master` has been reverted we just need to cut a new release - which is dependant on #337

**Comment by johanneswuerbach** [comment]
I think this change should be published asap (and marked as breaking) as it is advertised for ~ 2 months on your homepage and we (and I think others) already converted our projects to the new syntax.

**Comment by keithamus** [comment]
Yes, you're very right @johanneswuerbach. I'm going to work on getting a release out as soon as I can.

**Comment by sankethkatta** [comment]
@paul-barry-kenzan I was wondering the same thing. There seems to be some more context here: https://github.com/chaijs/chai/issues/371#issuecomment-75033714

**Pull request merged**
