### PR TITLE
Auto register side effects and Update documentation

### PR DESCRIPTION
**Pull request by deeperx**
An updating pull request for the new comments from the team: #868 

There was an earlier commits for this work, then, this is updating it.

### CODE REVIEW

**Comment by meeber** [comment]
Thanks for the PR! Couple nits for consistency:

- Switch **Pre-Native Modules Usage (_as local variables_)** examples to use single quotes instead of double.
- Add a semicolon to both `should()` statements.

**Comment by deeperx** [comment]
@meeber Thanks for reviewing. I updated it.

**Comment by meeber** [comment]
LGTM!

**Comment by lucasfcosta** [comment]
LGTM too!

**Pull request merged**
