### PR TITLE
chore: release 4.0.0-canary.2

### PR DESCRIPTION
**Pull request by keithamus**
@chaijs/chai 

Also we've broken 4000 stargazers, so 🎉 🍾

### CODE REVIEW

**Comment by meeber** [comment]
LGTM, but I recall we had an issue last time when merging and tagging a new canary release that caused it to automatically be marked as latest in npm. Do we know what caused that? Does it have to do with this: https://github.com/chaijs/chai/blob/526f88585d32220d3777053530ab3182af7bf5d0/.travis.yml#L22-L31

**Comment by keithamus** [comment]
@meeber yes I'm aware of the issues. Basically when we tag a commit, travis will automatically `npm pub`. It's a bit low-key but we can cancel the build before that happens, and manually publish - or alternatively let it publish `4.0.0-canary.2` to `latest` and then quickly run `npm dist-tag set chai@3.4.5 latest` and hope no one notices 😆

**Comment by keithamus** [comment]
So... I've commented out the deploy step. Travis wont deploy now. Once this is merged it'll need manually publishing as `npm pub --tag canary`. I will do this on my local machine once merged.

**Comment by meeber** [comment]
@keithamus Looks clear to proceed when you're ready!

**Comment by lucasfcosta** [comment]
Awesome job, everyone!
I can't wait to get `4.0.0` out!
You rock! 🍾

**Comment by keithamus** [comment]
FYI, just published this:

```bash
npm show chai

{ name: 'chai',
  description: 'BDD/TDD assertion library for node.js and the browser. Test framework agnostic.',
  'dist-tags': { latest: '3.5.0', canary: '4.0.0-canary.2' },
  --->8---
```

**Pull request merged**
