### PR TITLE
fix: ISSUE 1276: assert.doesNotDecreaseBy not work as expected

### PR DESCRIPTION
**Pull request by benben77**
fix the issue that `assert.doesNotDecreaseBy` does not works as expected / as described in docs

### CODE REVIEW

**Comment by rpgeeganage** [comment]
Hi,
Nice work!
But I'm wondering, why any of the tests are not breaking?
I guess it is better to have tests for this.

**Comment by benben77** [comment]
> Hi,
> Nice work!
> But I'm wondering, why any of the tests are not breaking?
> I guess it is better to have tests for this.

Oh you are right, it's weird that `doesNotDecreaseBy` is not covered in tests and there's no `doesNotIncreaseBy` 😂

**Comment by is2ei** [comment]
I think it doesn't need `doesNotDecreaseBy` since it has`decreasesButNotBy`.

**Comment by keithamus** [comment]
Can we please add some tests to assert this behaviour?

**Pull request closed without merging**
