### PR TITLE
Update sauce.browsers.js

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
I was expecting those Karma tests to run, but I see they didn't even run. Can someone please tell me why this was decided, please?

**Comment by keithamus** [comment]
Hey @mightyiam - thanks for updating the browsers. As for the karma tests not running on travis - I'm not sure it was a decision specifically to not run karma-sauce, just that when the commit (https://github.com/chaijs/chai/commit/e541116036a410568b2b3c024042d4ef503a9457) to add Karma Sauce was added, it was not added to `make test` - probably because at the time the stability of sauce tests was uncertain.

Please @mightyiam, feel free to extend this PR with adding support for running Karma Sauce through travis. It should be as simple as appending `test-sauce` to [L39 of makefile](https://github.com/chaijs/chai/blob/master/Makefile#L39). So the new line would like like:

```Makefile
test: test-node test-phantom test-sauce
```

**Comment by keithamus** [comment]
Hey @mightyiam, do you fancy updating this PR to change the makefile so the sauce tests run in Travis? It'll be really helpful if you can, and then I'll be happy to merge (provided tests pass of course :smile:)

**Comment by mightyiam** [comment]
@keithamus excuse me. This went off my radar unintentionally. Will do.

**Comment by keithamus** [comment]
Please take as much time as you need, was just a polite nudge :wink:

**Comment by keithamus** [comment]
Sorry @mightyiam - I just noticed that you've added this commit.

It seems like it's still testing the browsers. If you could take a look at it, great, otherwise I'll take a look sometime this week and figure out what's going on.

**Comment by mightyiam** [comment]
My Make–foo is insufficient.

**Comment by keithamus** [comment]
It's ok. I'll get on it at some point soon :smile:

**Comment by keithamus** [comment]
Oh I just noticed this can be closed, we tackled this in #614

**Pull request closed without merging**
