### PR TITLE
fixed expect('').to.contain('') so it passes

### PR DESCRIPTION
**Pull request by dereke**
Found a bug when you are trying to assert against a blank string.
Test case and fix included

### CODE REVIEW

**Comment by keithamus** [comment]
Hey @dereke, thanks for the PR. Could you please rebase your commits so as _not_ to include `chai.js`. It is built per-release and so shouldn't be built for individual PRs.

**Comment by dereke** [comment]
Hi @keithamus when we ran the tests without having build chai.js they failed.
Does CI build chai.js when the tests run?

**Comment by keithamus** [comment]
The CI does indeed run the tests: https://travis-ci.org/chaijs/chai/builds/78216305. Also, you're welcome to build chai.js as many times as you want locally, just don't commit it :wink:

**Comment by dereke** [comment]
OK cool. all done.

**Comment by dereke** [comment]
@keithamus when do you think this will show up in a release?

**Comment by keithamus** [comment]
Thanks for reminding me @dereke. I'm going to look at this in a couple of hours and make a release in about 5 hours, which will be 3.2.0 (hopefully)

**Comment by dereke** [comment]
any chance of publishing the new package?

**Comment by keithamus** [comment]
@dereke this should be in [`3.3.0`](https://github.com/chaijs/chai/releases/tag/3.3.0)

**Pull request merged**
