### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brutalcrozt**
Fix chai image, add 2 new badge -> issue resolution and open issue
coveralls.io in [maintain mode](https://coveralls.io/r/chaijs/chai) at this time

### CODE REVIEW

**Comment by keithamus** [comment]
Hey @brutalcrozt thanks for the PR.

Looks like you might have some old code - as the PR can't be merged. Could you please rebase the branch so that it is up to date.

**Comment by keithamus** [comment]
Also - we should keep the big logo, could you change the image url to be `http://chaijs.com/img/chai-logo.png` (without `-small`).

**Comment by brutalcrozt** [comment]
How stupid i am, one which confusing me is github show diff the broken img and i thought that i insert wrong code :smile: 

> @keithamus Also - we should keep the big logo, could you change the image url to be http://chaijs.com/img/chai-logo.png (without -small).

okay captain :smile:

**Comment by keithamus** [comment]
:+1: good job @brutalcrozt

**Pull request merged**
