### PR TITLE
chai@3.3.0

### PR DESCRIPTION
**Pull request by keithamus**
Thanks to @cezarykluczynski @astorije @Daveloper87 @wraithan @dereke and @kpdecker for all of your hard work!

### CODE REVIEW

**Comment by astorije** [comment]
Thank *you* for being so appreciative!

**Comment by techniq** [comment]
@keithamus `3.3.0` doesn't appear to be published to npm yet, can this happen soon? Hoping https://github.com/chaijs/chai/commit/b6b84e56317bc19ed8bd36609155f48c5a1103e8 fixes my issue

**Comment by techniq** [comment]
@keithamus looks like the npm publish is automated from travis, and the build failed due to SauceLab errors - https://travis-ci.org/chaijs/chai/builds/79929679

**Comment by techniq** [comment]
@keithamus any chance of getting this pushed to npm soon?

**Comment by keithamus** [comment]
Sorry @techniq! Published now.

**Comment by techniq** [comment]
@keithamus No problem.  Thanks

**Pull request merged**
