### PR TITLE
Define variable

### PR DESCRIPTION
**Pull request by aristov**
Global variable `html` leak possible.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
Hey @aristov, thanks for the PR.
Since FF < 12 is not supported by Chai, I think we should just do

```js
return value.outerHTML
```

**Comment by lucasfcosta** [comment]
Hi guys, thanks @aristov for the PR.
Well, I think you're right @shvaikalesh, if we don't support the browser for which we need this feature anymore we should just drop it.
Since I've just seen you made a new PR for that I'll give my LGTM seal of approval for this one and we can discuss this other change on the new PR 😄

**Comment by aristov** [comment]
@shvaikalesh @lucasfcosta 
open source works 👍

**Comment by keithamus** [comment]
Thanks for your contributions @aristov. Sorry we couldn't get this one merged, but it has definitely spurred some improvements, so thanks for making chai better 😄 🎉

**Pull request closed without merging**
