### PR TITLE
Fix `ownPropertyDescriptor` tests

### LINKED ISSUE #413: Tests failing due to #408
Hey @ljharb, the Travis job just failed because the tests in #408 seem to fail within Firefox 22. 

Here are the results from the build: https://travis-ci.org/chaijs/chai/builds/56420793

```js
Firefox 22.0.0 (Windows 7) expect ownPropertyDescriptor(name) FAILED
	expected 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { configurable: false,\n  enumerable: true,\n  value: NaN,\n  writable: true }' to equal 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { value: NaN,\n  writable: true,\n  enumerable: true,\n  configurable: false }'

Firefox 22.0.0 (Windows 7) expect ownPropertyDescriptor(name) FAILED
	expected 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { configurable: false,\n  enumerable: true,\n  value: NaN,\n  writable: true }' to equal 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { value: NaN,\n  writable: true,\n  enumerable: true,\n  configurable: false }'

Firefox 22.0.0 (Windows 7) should ownPropertyDescriptor(name) FAILED
	expected 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { configurable: false,\n  enumerable: true,\n  value: NaN,\n  writable: true }' to equal 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { value: NaN,\n  writable: true,\n  enumerable: true,\n  configurable: false }'

Firefox 22.0.0 (Windows 7) should ownPropertyDescriptor(name) FAILED
	expected 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { configurable: false,\n  enumerable: true,\n  value: NaN,\n  writable: true }' to equal 'blah: expected the own property descriptor for \'test\' on { test: NaN } to match { configurable: false,\n  enumerable: true,\n  writable: false,\n  value: NaN }, got { value: NaN,\n  writable: true,\n  enumerable: true,\n  configurable: false }'
```

To summarise them - it looks as though Firefox 22 just re-orders configuration properties strangely, so the strings that try to catch the error are wrong (because the properties are in the wrong order. It looks like its [expect.js#L550](https://github.com/chaijs/chai/blob/8b6a3ccb31623f019e9d28ee1f749280668613ef/test/expect.js#L550), and [expect.js#L559](https://github.com/chaijs/chai/blob/8b6a3ccb31623f019e9d28ee1f749280668613ef/test/expect.js#L559).

If you could address these in a new PR that'd awesome. Thanks @ljharb :smile:

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #413

### CODE REVIEW

**Comment by keithamus** [comment]
Great work @ljharb :smile:

But, can you drop the last commit please. `make build` is only run per-release.

**Comment by ljharb** [comment]
Done!

**Comment by keithamus** [comment]
:+1:

**Comment by ljharb** [comment]
Thanks!

**Pull request merged**
