### PR TITLE
docs: fix link to OpenCollective

### PR DESCRIPTION
**Pull request by keithamus**
I think we were... okay I was... a bit hasty on merging this. The link went no where. This one goes to our Open Collective page. #732

### CODE REVIEW

**Comment by meeber** [comment]
LGTM

**Comment by lucasfcosta** [comment]
Oh, I didn't notice this too.
I should've checked the link.
Well, now everything is working, our OpenCollective page is very nice BTW.

LGTM.

**Comment by keithamus** [comment]
I may have to disable the check for travis considering how flaky our tests are and they prevent merging

**Comment by lucasfcosta** [comment]
@keithamus Makes sense, since we can't run builds on IE for PRs there's no way we can ensure tests will pass both on the PR check and the check after a merge. However, I'd prefer keeping these checks and having to run builds on IE manually on my machine just to make sure everything passes. I think this could now be a new default step of the merge process since we would have to clone the forks and run tests locally anyway before merging.

Thoughts @meeber and @keithamus ?

**Comment by meeber** [comment]
I'd like to keep the checks. They encourage us to fix whatever browser-specific problem popped up from previous PR before moving on.

**Comment by keithamus** [comment]
@meeber We can keep the checks, but right now if the check fails it prevents from merging which means small changes like this get blocked until an admin merges or the tests pass and the pr is rebased. I just wanted to disable the gate that would prevent one of you two merging should the build fail.

**Pull request merged**
