### PR TITLE
Integrate `chai-subset` into chai core

### PR DESCRIPTION
**Pull request by koddsson**
I tried to make sure to preserve the `chai-subset` history when doing this.

Fixes https://github.com/chaijs/chai/issues/1616

### CODE REVIEW

**Comment by 43081j** [comment]
it looks good to me but i have a couple of thoughts:

1 - i know you put effort into keeping the git history but i'd actually squash this anyway if we merge it as i don't think the subset history makes sense in our tree. it may be better to just note somewhere this was originally built by andrii

2 - something's bugging me about the overlap here of `includes`. we have basically the same algorithm in `includes` (written differently) than we do here, but in that one we don't do partial equality on the deep properties.

i wonder if we can at least extract the traversal logic so they both share it, or we make `includes` have a flag that achieves what subset does. im cautious of putting too much logic in `includes` though as its already a pretty big, multi-use assertion.

**Comment by keithamus** [comment]
> 2 - something's bugging me about the overlap here of `includes`.

We'll likely have similar logic in `deep-eql` too. I'll add that `deep-eql` is also very well optimised. I wonder if we can leverage it and it's custom comparators to effectively traverse the first layer?

**Comment by koddsson** [comment]
I'll start looking at squaring this up according to the comments.

**Comment by koddsson** [comment]
I'm cleaning up some old PRs and am gonna close this. I'll re-open a different one if I end up working on this.

**Pull request closed without merging**
